/*
Package oci implements a steampipe plugin for OCI.

This plugin provides data that Steampipe uses to present foreign
tables that represent Oracle Cloud Infrastructure resources.
*/
package oci

import (
	"context"

	"github.com/turbot/steampipe-plugin-sdk/v3/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v3/plugin/transform"
)

const pluginName = "steampipe-plugin-oci"

// Plugin creates this (oci) plugin
func Plugin(ctx context.Context) *plugin.Plugin {
	p := &plugin.Plugin{
		Name:             pluginName,
		DefaultTransform: transform.FromGo(),
		DefaultGetConfig: &plugin.GetConfig{
			ShouldIgnoreError: isNotFoundError([]string{"404"}),
		},
		ConnectionConfigSchema: &plugin.ConnectionConfigSchema{
			NewInstance: ConfigInstance,
			Schema:      ConfigSchema,
		},
		TableMap: map[string]*plugin.Table{
			"oci_analytics_instance":                                       tableAnalyticsInstance(ctx),
			"oci_apigateway_api":                                           tableApiGatewayApi(ctx),
			"oci_autoscaling_auto_scaling_configuration":                   tableAutoScalingConfiguration(ctx),
			"oci_budget_alert_rule":                                        tableBudgetAlertRule(ctx),
			"oci_budget_budget":                                            tableBudget(ctx),
			"oci_cloud_guard_configuration":                                tableCloudGuardConfiguration(ctx),
			"oci_cloud_guard_detector_recipe":                              tableCloudGuardDetectorRecipe(ctx),
			"oci_cloud_guard_managed_list":                                 tableCloudGuardManagedList(ctx),
			"oci_cloud_guard_responder_recipe":                             tableCloudGuardResponderRecipe(ctx),
			"oci_cloud_guard_target":                                       tableCloudGuardTarget(ctx),
			"oci_containerengine_cluster":                                  tableOciContainerEngineCluster(ctx),
			"oci_core_block_volume_replica":                                tableCoreBlockVolumeReplica(ctx),
			"oci_core_boot_volume":                                         tableCoreBootVolume(ctx),
			"oci_core_boot_volume_attachment":                              tableCoreBootVolumeAttachment(ctx),
			"oci_core_boot_volume_backup":                                  tableCoreBootVolumeBackup(ctx),
			"oci_core_boot_volume_metric_read_ops":                         tableOciCoreBootVolumeMetricReadOps(ctx),
			"oci_core_boot_volume_metric_read_ops_daily":                   tableOciCoreBootVolumeMetricReadOpsDaily(ctx),
			"oci_core_boot_volume_metric_read_ops_hourly":                  tableOciCoreBootVolumeMetricReadOpsHourly(ctx),
			"oci_core_boot_volume_metric_write_ops":                        tableOciCoreBootVolumeMetricWriteOps(ctx),
			"oci_core_boot_volume_metric_write_ops_daily":                  tableOciCoreBootVolumeMetricWriteOpsDaily(ctx),
			"oci_core_boot_volume_metric_write_ops_hourly":                 tableOciCoreBootVolumeMetricWriteOpsHourly(ctx),
			"oci_core_boot_volume_replica":                                 tableCoreBootVolumeReplica(ctx),
			"oci_core_dhcp_options":                                        tableCoreDhcpOptions(ctx),
			"oci_core_drg":                                                 tableCoreDrg(ctx),
			"oci_core_image":                                               tableCoreImage(ctx),
			"oci_core_image_custom":                                        tableCoreImageCustom(ctx),
			"oci_core_instance":                                            tableCoreInstance(ctx),
			"oci_core_instance_metric_cpu_utilization":                     tableOciCoreInstanceMetricCpuUtilization(ctx),
			"oci_core_instance_metric_cpu_utilization_daily":               tableOciCoreInstanceMetricCpuUtilizationDaily(ctx),
			"oci_core_instance_metric_cpu_utilization_hourly":              tableOciCoreInstanceMetricCpuUtilizationHourly(ctx),
			"oci_core_internet_gateway":                                    tableCoreInternetGateway(ctx),
			"oci_core_load_balancer":                                       tableCoreLoadBalancer(ctx),
			"oci_core_local_peering_gateway":                               tableCoreLocalPeeringGateway(ctx),
			"oci_core_nat_gateway":                                         tableCoreNatGateway(ctx),
			"oci_core_network_load_balancer":                               tableCoreNetworkLoadBalancer(ctx),
			"oci_core_network_security_group":                              tableCoreNetworkSecurityGroup(ctx),
			"oci_core_public_ip":                                           tableCorePublicIP(ctx),
			"oci_core_public_ip_pool":                                      tableCorePublicIPPool(ctx),
			"oci_core_route_table":                                         tableCoreRouteTable(ctx),
			"oci_core_security_list":                                       tableCoreSecurityList(ctx),
			"oci_core_service_gateway":                                     tableCoreServiceGateway(ctx),
			"oci_core_subnet":                                              tableCoreSubnet(ctx),
			"oci_core_vcn":                                                 tableCoreVcn(ctx),
			"oci_core_vnic_attachment":                                     tableCoreVnicAttachment(ctx),
			"oci_core_volume":                                              tableCoreVolume(ctx),
			"oci_core_volume_attachment":                                   tableCoreVolumeAttachment(ctx),
			"oci_core_volume_backup":                                       tableCoreVolumeBackup(ctx),
			"oci_core_volume_backup_policy":                                tableCoreVolumeBackupPolicy(ctx),
			"oci_database_autonomous_database":                             tableOciDatabaseAutonomousDatabase(ctx),
			"oci_database_autonomous_db_metric_cpu_utilization":            tableOciDatabaseAutonomousDatabaseMetricCpuUtilization(ctx),
			"oci_database_autonomous_db_metric_cpu_utilization_daily":      tableOciDatabaseAutonomousDatabaseMetricCpuUtilizationDaily(ctx),
			"oci_database_autonomous_db_metric_cpu_utilization_hourly":     tableOciDatabaseAutonomousDatabaseMetricCpuUtilizationHourly(ctx),
			"oci_database_autonomous_db_metric_storage_utilization":        tableOciDatabaseAutonomousDatabaseMetricStorageUtilization(ctx),
			"oci_database_autonomous_db_metric_storage_utilization_daily":  tableOciDatabaseAutonomousDatabaseMetricStorageUtilizationDaily(ctx),
			"oci_database_autonomous_db_metric_storage_utilization_hourly": tableOciDatabaseAutonomousDatabaseMetricStorageUtilizationHourly(ctx),
			"oci_database_db":                                              tableOciDatabase(ctx),
			"oci_database_db_home":                                         tableOciDatabaseDBHome(ctx),
			"oci_database_db_system":                                       tableOciDatabaseDBSystem(ctx),
			"oci_database_pluggable_database":                              tableOciPluggableDatabase(ctx),
			"oci_database_software_image":                                  tableOciDatabaseSoftwareImage(ctx),
			"oci_dns_rrset":                                                tableDnsRecordSet(ctx),
			"oci_dns_tsig_key":                                             tableDnsTsigKey(ctx),
			"oci_dns_zone":                                                 tableDnsZone(ctx),
			"oci_events_rule":                                              tableEventsRule(ctx),
			"oci_file_storage_file_system":                                 tableFileStorageFileSystem(ctx),
			"oci_file_storage_mount_target":                                tableFileStorageMountTarget(ctx),
			"oci_file_storage_snapshot":                                    tableFileStorageSnapshot(ctx),
			"oci_functions_application":                                    tableFunctionsApplication(ctx),
			"oci_functions_function":                                       tableFunctionsFunction(ctx),
			"oci_identity_api_key":                                         tableIdentityApiKey(ctx),
			"oci_identity_auth_token":                                      tableIdentityAuthToken(ctx),
			"oci_identity_authentication_policy":                           tableIdentityAuthenticationPolicy(ctx),
			"oci_identity_availability_domain":                             tableIdentityAvailabilityDomain(ctx),
			"oci_identity_compartment":                                     tableIdentityCompartment(ctx),
			"oci_identity_customer_secret_key":                             tableIdentityCustomerSecretKey(ctx),
			"oci_identity_dynamic_group":                                   tableIdentityDynamicGroup(ctx),
			"oci_identity_group":                                           tableIdentityGroup(ctx),
			"oci_identity_network_source":                                  tableIdentityNetworkSource(ctx),
			"oci_identity_policy":                                          tableIdentityPolicy(ctx),
			"oci_identity_tag_default":                                     tableIdentityTagDefault(ctx),
			"oci_identity_tag_namespace":                                   tableIdentityTagNamespace(ctx),
			"oci_identity_tenancy":                                         tableIdentityTenancy(ctx),
			"oci_identity_user":                                            tableIdentityUser(ctx),
			"oci_kms_key":                                                  tableKmsKey(ctx),
			"oci_kms_key_version":                                          tableKmsKeyVersion(ctx),
			"oci_kms_vault":                                                tableKmsVault(ctx),
			"oci_limits_quota":                                             tableLimitsQuota(ctx),
			"oci_logging_log":                                              tableLoggingLog(ctx),
			"oci_logging_log_group":                                        tableLoggingLogGroup(ctx),
			"oci_mysql_backup":                                             tableMySQLBackup(ctx),
			"oci_mysql_channel":                                            tableMySQLChannel(ctx),
			"oci_mysql_configuration":                                      tableMySQLConfiguration(ctx),
			"oci_mysql_configuration_custom":                               tableMySQLConfigurationCustom(ctx),
			"oci_mysql_db_system":                                          tableMySQLDBSystem(ctx),
			"oci_mysql_db_system_metric_connections":                       tableOciMySQLDBSystemMetricConnections(ctx),
			"oci_mysql_db_system_metric_connections_daily":                 tableOciMySQLDBSystemMetricConnectionsDaily(ctx),
			"oci_mysql_db_system_metric_connections_hourly":                tableOciMySQLDBSystemMetricConnectionsHourly(ctx),
			"oci_mysql_db_system_metric_cpu_utilization":                   tableOciMySQLDBSystemMetricCpuUtilization(ctx),
			"oci_mysql_db_system_metric_cpu_utilization_daily":             tableOciMySQLDBSystemMetricCpuUtilizationDaily(ctx),
			"oci_mysql_db_system_metric_cpu_utilization_hourly":            tableOciMySQLDBSystemMetricCpuUtilizationHourly(ctx),
			"oci_mysql_db_system_metric_memory_utilization":                tableOciMySQLDBSystemMetricMemoryUtilization(ctx),
			"oci_mysql_db_system_metric_memory_utilization_daily":          tableOciMySQLDBSystemMetricMemoryUtilizationDaily(ctx),
			"oci_mysql_heat_wave_cluster":                                  tableOciMySQLHeatWaveCluster(ctx),
			"oci_nosql_table":                                              tableNoSQLTable(ctx),
			"oci_nosql_table_metric_read_throttle_count":                   tableOciNoSQLTableMetricReadThrottleCount(ctx),
			"oci_nosql_table_metric_read_throttle_count_daily":             tableOciNoSQLTableMetricReadThrottleCountDaily(ctx),
			"oci_nosql_table_metric_read_throttle_count_hourly":            tableOciNoSQLTableMetricReadThrottleCountHourly(ctx),
			"oci_nosql_table_metric_storage_utilization":                   tableOciNoSQLTableMetricStorageUtilization(ctx),
			"oci_nosql_table_metric_storage_utilization_daily":             tableOciNoSQLTableMetricStorageUtilizationDaily(ctx),
			"oci_nosql_table_metric_storage_utilization_hourly":            tableOciNoSQLTableMetricStorageUtilizationHourly(ctx),
			"oci_nosql_table_metric_write_throttle_count":                  tableOciNoSQLTableMetricWriteThrottleCount(ctx),
			"oci_nosql_table_metric_write_throttle_count_daily":            tableOciNoSQLTableMetricWriteThrottleCountDaily(ctx),
			"oci_nosql_table_metric_write_throttle_count_hourly":           tableOciNoSQLTableMetricWriteThrottleCountHourly(ctx),
			"oci_objectstorage_bucket":                                     tableObjectStorageBucket(ctx),
			"oci_objectstorage_object":                                     tableObjectStorageObject(ctx),
			"oci_ons_notification_topic":                                   tableOnsNotificationTopic(ctx),
			"oci_ons_subscription":                                         tableOnsSubscription(ctx),
			"oci_region":                                                   tableIdentityRegion(ctx),
			"oci_resource_search":                                          tableResourceSearch(ctx),
			"oci_resourcemanager_stack":                                    tableOciResourceManagerStack(ctx),
			"oci_streaming_stream":                                         tableOciStreamingStream(ctx),
			"oci_vault_secret":                                             tableVaultSecret(ctx),
		},
	}
	return p
}
