package oci

import (
	"context"

	"github.com/oracle/oci-go-sdk/v65/cloudmigrations"
	"github.com/oracle/oci-go-sdk/v65/common"
	"github.com/turbot/go-kit/types"
	"github.com/turbot/steampipe-plugin-sdk/v5/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin/transform"
)

func tableCloudMigrationsMigrationAsset(_ context.Context) *plugin.Table {
	return &plugin.Table{
		Name:             "oci_cloud_migrations_migration_asset",
		Description:      "OCI Cloud Migrations Migration Asset.",
		DefaultTransform: transform.FromCamel(),
		List: &plugin.ListConfig{
			Hydrate:       listCloudMigrationsMigrationAssets,
			ParentHydrate: listCloudMigrationsMigrations,
			KeyColumns: []*plugin.KeyColumn{
				{Name: "migration_id", Require: plugin.Optional},
				{Name: "display_name", Require: plugin.Optional},
				{Name: "lifecycle_state", Require: plugin.Optional},
			},
		},
		Get: &plugin.GetConfig{
			KeyColumns: plugin.SingleColumn("id"),
			Hydrate:    getCloudMigrationsMigrationAsset,
		},
		GetMatrixItemFunc: BuildCompartementRegionList,
		Columns: commonColumnsForAllResource([]*plugin.Column{
			{
				Name:        "id",
				Type:        proto.ColumnType_STRING,
				Description: "Asset ID generated by migration service. It is used in the migration service pipeline.",
			},
			{
				Name:        "migration_id",
				Type:        proto.ColumnType_STRING,
				Description: "OCID of the associated migration.",
			},
			{
				Name:        "type",
				Type:        proto.ColumnType_STRING,
				Description: "The type of asset referenced for inventory.",
			},
			{
				Name:        "display_name",
				Type:        proto.ColumnType_STRING,
				Description: "A user-friendly name. Does not have to be unique, and it's changeable.",
			},
			{
				Name:        "lifecycle_state",
				Type:        proto.ColumnType_STRING,
				Description: "The current state of the migration asset.",
			},
			{
				Name:        "lifecycle_details",
				Type:        proto.ColumnType_STRING,
				Description: "A message describing the current state in more detail.",
			},
			{
				Name:        "time_created",
				Type:        proto.ColumnType_TIMESTAMP,
				Description: "The time when the migration asset was created.",
				Transform:   transform.FromField("TimeCreated.Time"),
			},
			{
				Name:        "time_updated",
				Type:        proto.ColumnType_TIMESTAMP,
				Description: "The time when the migration asset was updated.",
				Transform:   transform.FromField("TimeUpdated.Time"),
			},
			{
				Name:        "availability_domain",
				Type:        proto.ColumnType_STRING,
				Description: "Availability domain.",
			},
			{
				Name:        "replication_compartment_id",
				Type:        proto.ColumnType_STRING,
				Description: "Replication compartment identifier.",
			},
			{
				Name:        "snap_shot_bucket_name",
				Type:        proto.ColumnType_STRING,
				Description: "Name of snapshot bucket.",
			},
			{
				Name:        "snapshots",
				Type:        proto.ColumnType_JSON,
				Description: "Key-value pair representing disks ID mapped to the OCIDs of replicated or hydration server volume snapshots.",
			},
			{
				Name:        "parent_snapshot",
				Type:        proto.ColumnType_STRING,
				Description: "The parent snapshot of the migration asset to be used by the replication task.",
			},
			{
				Name:        "source_asset_data",
				Type:        proto.ColumnType_JSON,
				Description: "Key-value pair representing asset metadata keys and values scoped to a namespace.",
			},
			{
				Name:        "notifications",
				Type:        proto.ColumnType_JSON,
				Description: "List of notifications.",
			},
			{
				Name:        "source_asset_id",
				Type:        proto.ColumnType_STRING,
				Description: "OCID that is referenced to an asset for an inventory.",
			},
			{
				Name:        "replication_schedule_id",
				Type:        proto.ColumnType_STRING,
				Description: "Replication schedule identifier.",
			},
			{
				Name:        "tenancy_id",
				Type:        proto.ColumnType_STRING,
				Description: "Tenancy identifier.",
			},
			{
				Name:        "depended_on_by",
				Type:        proto.ColumnType_JSON,
				Description: "List of migration assets that depend on the asset.",
			},
			{
				Name:        "depends_on",
				Type:        proto.ColumnType_JSON,
				Description: "List of migration assets that depends on the asset.",
			},
			{
				Name:        "freeform_tags",
				Type:        proto.ColumnType_JSON,
				Description: ColumnDescriptionFreefromTags,
			},
			{
				Name:        "defined_tags",
				Type:        proto.ColumnType_JSON,
				Description: ColumnDescriptionDefinedTags,
			},
			{
				Name:        "system_tags",
				Type:        proto.ColumnType_JSON,
				Description: ColumnDescriptionSystemTags,
			},

			// Standard Steampipe columns
			{
				Name:        "title",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("DisplayName"),
				Description: ColumnDescriptionTitle,
			},

			// Standard OCI columns
			{
				Name:        "region",
				Description: ColumnDescriptionRegion,
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Id").Transform(ociRegionName),
			},
			{
				Name:        "compartment_id",
				Description: ColumnDescriptionCompartment,
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("CompartmentId"),
			},
			{
				Name:        "tenant_id",
				Description: ColumnDescriptionTenantId,
				Type:        proto.ColumnType_STRING,
				Hydrate:     getTenantId,
				Transform:   transform.FromValue(),
			},
		}),
	}
}

func listCloudMigrationsMigrationAssets(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
	migration := h.Item.(cloudmigrations.MigrationSummary)

	logger := plugin.Logger(ctx)
	region := d.EqualsQualString(matrixKeyRegion)
	logger.Debug("oci_cloud_migrations_migration_asset.listCloudMigrationsMigrationAssets", "OCI_REGION", region)

	equalQuals := d.EqualsQuals
	if equalQuals["migration_id"] != nil && equalQuals["migration_id"].GetStringValue() != *migration.Id {
		return nil, nil
	}

	session, err := cloudMigrationsService(ctx, d, region)
	if err != nil {
		logger.Error("oci_cloud_migrations_migration_asset.listCloudMigrationsMigrationAssets", "connection_error", err)
		return nil, err
	}

	request := cloudmigrations.ListMigrationAssetsRequest{
		MigrationId: migration.Id,
		Limit:       types.Int(100),
		RequestMetadata: common.RequestMetadata{
			RetryPolicy: getDefaultRetryPolicy(d.Connection),
		},
	}

	// Handle optional quals
	if equalQuals["display_name"] != nil {
		displayName := equalQuals["display_name"].GetStringValue()
		request.DisplayName = types.String(displayName)
	}

	if equalQuals["lifecycle_state"] != nil {
		lifecycleState := equalQuals["lifecycle_state"].GetStringValue()
		request.LifecycleState = cloudmigrations.MigrationAssetLifecycleStateEnum(lifecycleState)
	}

	// Handle limit
	limit := d.QueryContext.Limit
	if d.QueryContext.Limit != nil {
		if *limit < int64(*request.Limit) {
			request.Limit = types.Int(int(*limit))
		}
	}

	pagesLeft := true
	for pagesLeft {
		response, err := session.CloudMigrationsClient.ListMigrationAssets(ctx, request)
		if err != nil {
			logger.Error("oci_cloud_migrations_migration_asset.listCloudMigrationsMigrationAssets", "api_error", err)
			return nil, err
		}
		for _, item := range response.Items {
			d.StreamListItem(ctx, item)
			if d.RowsRemaining(ctx) == 0 {
				return nil, nil
			}
		}
		if response.OpcNextPage != nil {
			request.Page = response.OpcNextPage
		} else {
			pagesLeft = false
		}
	}
	return nil, nil
}

func getCloudMigrationsMigrationAsset(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
	logger := plugin.Logger(ctx)
	region := d.EqualsQualString(matrixKeyRegion)
	logger.Debug("oci_cloud_migrations_migration_asset.getCloudMigrationsMigrationAsset", "OCI_REGION", region)

	var id string
	if h.Item != nil {
		id = *h.Item.(cloudmigrations.MigrationAssetSummary).Id
	} else {
		id = d.EqualsQuals["id"].GetStringValue()
	}
	if id == "" {
		return nil, nil
	}

	session, err := cloudMigrationsService(ctx, d, region)
	if err != nil {
		logger.Error("oci_cloud_migrations_migration_asset.getCloudMigrationsMigrationAsset", "connection_error", err)
		return nil, err
	}

	request := cloudmigrations.GetMigrationAssetRequest{
		MigrationAssetId: types.String(id),
		RequestMetadata: common.RequestMetadata{
			RetryPolicy: getDefaultRetryPolicy(d.Connection),
		},
	}

	response, err := session.CloudMigrationsClient.GetMigrationAsset(ctx, request)
	if err != nil {
		logger.Error("oci_cloud_migrations_migration_asset.getCloudMigrationsMigrationAsset", "api_error", err)
		return nil, err
	}
	return response.MigrationAsset, nil
}
